# Generated by Django 2.1.2 on 2019-02-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download_options',
            name='name',
        ),
    ]
