# Generated by Django 2.1.2 on 2019-02-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0002_remove_download_options_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_options',
            name='first_name',
            field=models.BooleanField(default=None, verbose_name='Patient First Name'),
        ),
        migrations.AddField(
            model_name='download_options',
            name='last_name',
            field=models.BooleanField(default=None, verbose_name='Patient Last Name'),
        ),
    ]
