# Generated by Django 2.1.2 on 2019-03-03 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0004_download_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_options',
            name='accession_number',
            field=models.BooleanField(default=None, verbose_name='Accession Number'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 21, 55, 28, 971688)),
        ),
    ]
