# Generated by Django 2.1.2 on 2019-03-03 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0005_auto_20190303_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_options',
            name='DOB',
            field=models.BooleanField(default=None, verbose_name='Patient DOB'),
        ),
        migrations.AlterField(
            model_name='download_options',
            name='MRN',
            field=models.BooleanField(default=None, verbose_name='Patient MRN'),
        ),
        migrations.AlterField(
            model_name='download_options',
            name='age',
            field=models.BooleanField(default=None, verbose_name='Patient Age'),
        ),
        migrations.AlterField(
            model_name='download_options',
            name='date',
            field=models.BooleanField(default=None, verbose_name='Accession Date'),
        ),
        migrations.AlterField(
            model_name='download_options',
            name='sex',
            field=models.BooleanField(default=None, verbose_name='Patient Sex'),
        ),
        migrations.AlterField(
            model_name='download_options',
            name='staff',
            field=models.BooleanField(default=None, verbose_name='Assigned Staff'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 21, 58, 10, 176677)),
        ),
    ]
