# Generated by Django 2.1.2 on 2019-03-03 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0006_auto_20190303_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_options',
            name='accession_number',
            field=models.BooleanField(default=False, verbose_name='Accession Number'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 22, 1, 27, 900989)),
        ),
    ]
