# Generated by Django 2.1.2 on 2019-03-03 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0008_auto_20190303_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_request',
            name='DOB',
            field=models.BooleanField(default=False, verbose_name='Patient DOB'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='MRN',
            field=models.BooleanField(default=False, verbose_name='Patient MRN'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='accession_number',
            field=models.BooleanField(default=False, verbose_name='Accession Number'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='age',
            field=models.BooleanField(default=False, verbose_name='Patient Age'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='date',
            field=models.BooleanField(default=False, verbose_name='Accession Date'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 22, 41, 54, 56779)),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='first_name',
            field=models.BooleanField(default=False, verbose_name='Patient First Name'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='last_name',
            field=models.BooleanField(default=False, verbose_name='Patient Last Name'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='sex',
            field=models.BooleanField(default=False, verbose_name='Patient Sex'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Assigned Staff'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='text',
            field=models.BooleanField(default=False, verbose_name='Diagnostic Text'),
        ),
    ]
