# Generated by Django 2.1.2 on 2019-03-04 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0011_auto_20190304_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 20, 29, 21, 646427)),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
