# Generated by Django 2.1.2 on 2019-03-04 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0012_auto_20190304_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download_request',
            name='user',
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 21, 38, 12, 498779)),
        ),
    ]
