# Generated by Django 2.1.2 on 2019-03-04 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0013_auto_20190304_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='email',
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AddField(
            model_name='download_request',
            name='username',
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 21, 40, 11, 375640)),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='query',
            field=models.CharField(default=False, max_length=256),
        ),
    ]
