# Generated by Django 2.1.2 on 2019-03-05 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0014_auto_20190304_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='collection_sheet',
            field=models.FileField(default='test', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 3, 45, 1, 49162)),
        ),
    ]
