# Generated by Django 2.1.2 on 2019-03-14 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0015_auto_20190305_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download_request',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='last_name',
        ),
        migrations.AddField(
            model_name='download_request',
            name='name',
            field=models.BooleanField(default=False, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 2, 27, 53, 449844)),
        ),
    ]
