# Generated by Django 2.1.2 on 2019-03-14 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0016_auto_20190314_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='user_first',
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AddField(
            model_name='download_request',
            name='user_last',
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 2, 59, 43, 761229)),
        ),
    ]
