# Generated by Django 2.1.2 on 2019-03-16 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0017_auto_20190314_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='pending',
            field=models.BooleanField(default=True, verbose_name='Pending'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 23, 31, 25, 13688)),
        ),
    ]
