# Generated by Django 2.1.2 on 2019-03-18 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0020_auto_20190318_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='execute_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 18, 45, 28, 574704), verbose_name='Execute Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 18, 45, 28, 574657), verbose_name='Request Timestamp'),
        ),
    ]
