# Generated by Django 2.1.2 on 2019-03-18 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0021_auto_20190318_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_request',
            name='execute_datetime',
            field=models.DateTimeField(verbose_name='Execute Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='execute_user',
            field=models.CharField(max_length=256, verbose_name='Executed By'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 19, 4, 18, 178244), verbose_name='Request Timestamp'),
        ),
    ]
