# Generated by Django 2.1.2 on 2019-03-18 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0022_auto_20190318_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_request',
            name='execute_datetime',
            field=models.DateTimeField(null=True, verbose_name='Execute Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 19, 10, 6, 118864), verbose_name='Request Timestamp'),
        ),
    ]
