# Generated by Django 2.1.2 on 2019-03-19 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0023_auto_20190318_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejected'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 19, 13, 40, 108747), verbose_name='Request Timestamp'),
        ),
    ]
