# Generated by Django 2.1.2 on 2019-04-12 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0024_auto_20190319_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 20, 52, 12, 875685), verbose_name='Request Timestamp'),
        ),
    ]
