# Generated by Django 2.1.2 on 2019-04-12 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0025_auto_20190412_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='clinical',
            field=models.BooleanField(default=False, verbose_name='Clinical Information'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 20, 54, 43, 708184), verbose_name='Request Timestamp'),
        ),
    ]
