# Generated by Django 2.1.2 on 2019-04-12 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0026_auto_20190412_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='gross',
            field=models.BooleanField(default=False, verbose_name='Gross Description'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='intraoperative',
            field=models.BooleanField(default=False, verbose_name='Intraoperative Diagnosis'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='synoptic',
            field=models.BooleanField(default=False, verbose_name='Synoptic'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 21, 0, 11, 734221), verbose_name='Request Timestamp'),
        ),
    ]
