# Generated by Django 2.1.2 on 2019-04-18 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0027_auto_20190412_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 20, 59, 17, 790201), verbose_name='Request Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='text',
            field=models.BooleanField(default=False, verbose_name='Final, Comment, Addendums'),
        ),
    ]
