# Generated by Django 2.1.2 on 2019-05-27 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0028_auto_20190418_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_options',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Assigned Staff (not considered PHI)'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 27, 17, 16, 21, 711733), verbose_name='Request Timestamp'),
        ),
    ]
