# Generated by Django 2.1.2 on 2019-05-30 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0031_auto_20190530_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_request',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 23, 22, 24, 143305), verbose_name='Request Timestamp'),
        ),
    ]
