# Generated by Django 2.1.2 on 2019-06-04 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0032_auto_20190530_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download_Options',
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 2, 6, 26, 493379), verbose_name='Request Timestamp'),
        ),
    ]
