# Generated by Django 2.1.2 on 2019-07-31 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0034_auto_20190605_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download_request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='user_first',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='user_last',
        ),
        migrations.AddField(
            model_name='download_request',
            name='request_type',
            field=models.CharField(choices=[('IRB', 'IRB'), ('Case_Finding', 'Case_Finding')], default='IRB', max_length=20),
        ),
        migrations.AddField(
            model_name='download_request',
            name='user_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='download_request',
            name='user_first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='download_request',
            name='user_last_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='IRB_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='collection_sheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='notes',
            field=models.TextField(default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='query',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 1, 34, 41, 511324), verbose_name='Request Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
