# Generated by Django 2.1.2 on 2020-01-03 23:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dx_search', '0036_auto_20190805_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2020, 1, 3, 23, 46, 36, 965690), verbose_name='Creation Timestamp')),
                ('cases', models.ManyToManyField(to='dx_search.Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='name',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='new',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='query',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='user_last_name',
        ),
        migrations.RemoveField(
            model_name='download_request',
            name='username',
        ),
        migrations.AddField(
            model_name='download_request',
            name='analyst_request',
            field=models.BooleanField(default=False, verbose_name='Analyst Request'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='first_name',
            field=models.BooleanField(default=False, verbose_name='Patient First Name'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='last_name',
            field=models.BooleanField(default=False, verbose_name='Patient Last Name'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='requestor_email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='download_request',
            name='requestor_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='download_request',
            name='requestor_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='download_request',
            name='specimen_class',
            field=models.BooleanField(default=False, verbose_name='Copath Specimen Class'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='specimen_type',
            field=models.BooleanField(default=False, verbose_name='Specimen Type (sp, cyto, bone marrow)'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='New', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='user',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 23, 46, 36, 967362), verbose_name='Request Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_type',
            field=models.CharField(choices=[('IRB', 'IRB'), ('Case_Finding', 'Case_Finding')], default='IRB', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Assigned Staff'),
        ),
        migrations.AddField(
            model_name='download_request',
            name='case_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secondar_User', to='dx_search.Case_Set'),
        ),
    ]
