# Generated by Django 2.1.2 on 2020-02-24 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0038_auto_20200224_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_set',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 13, 46, 39, 739801), verbose_name='Creation Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 13, 46, 39, 746081), verbose_name='Request Timestamp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 13, 46, 39, 738715), verbose_name='Last Password Change'),
        ),
    ]
