# Generated by Django 2.1.2 on 2021-01-25 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0042_auto_20210125_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_set',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 15, 57, 17, 363065), verbose_name='Creation Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 15, 57, 17, 365937), verbose_name='Request Timestamp'),
        ),
        migrations.AlterField(
            model_name='download_request',
            name='request_type',
            field=models.CharField(choices=[('IRB', 'Research with IRB'), ('Case_Finding', 'Not Research (Case-Finding)')], default='IRB', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 15, 57, 17, 361017), verbose_name='Last Password Change'),
        ),
    ]
