# Generated by Django 2.1.2 on 2019-02-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dx_search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download_Options',
        ),
    ]
